-- Retrieve all records from the CustomerPurchaseData dataset?
select * from CustomerPurchaseData;

-- Find the average purchase amount (in USD) for all transactions.
select avg([Purchase Amount (USD)]) as "Average Purchase Amount" from CustomerPurchaseData;

-- List unique payment methods used by customers?
select distinct [Payment Method] from CustomerPurchaseData;

-- Count the number of purchases made in each season?
select season, count(*) as "Number Of Purchases" from CustomerPurchaseData group by Season;

-- Calculate the total purchase amount (in USD) for each category?
select category, sum([Purchase Amount (USD)]) as "Total Purchase Amount" from CustomerPurchaseData group by Category;

-- Retrieve the highest purchase amount (in USD) and the corresponding item purchased?
select top 1 [Item Purchased], [Purchase Amount (USD)] from CustomerPurchaseData order by [Purchase Amount (USD)] desc;

-- Determine the average review rating for each category?
select category, avg([Review Rating]) as "Average Review Rating" from CustomerPurchaseData group by category;

-- Count the number of purchases made by male and female customers?
select gender, count(*) as "Number Of Purchases" from CustomerPurchaseData group by gender;

-- Calculate the total purchase amount (in USD) for each payment method?
select [Payment Method], sum([Purchase Amount (USD)]) as "Total Purchase Amount" from CustomerPurchaseData group by [Payment Method];

-- Find the most preferred payment method by customers?
select [Preferred Payment Method], count(*) as "Preference Count" from CustomerPurchaseData group by [Preferred Payment Method]
order by "Preference Count" desc;

-- Calculate the total revenue generated by each category, including the average purchase amount and the total number of purchases for each category.
select category, count(*) as "Number Of Purchases", avg([Purchase Amount (USD)]) as "Average Purchase Amount",
sum([Purchase Amount (USD)]) as "Total Revenue" from CustomerPurchaseData group by category;

-- Identify the most popular item (highest number of purchases) in each category?
select category, [Item Purchased] as "Most Popular Item", count(*) as "Number Of Purchases" from CustomerPurchaseData
group by category, [Item Purchased] having count(*) = (select max(ItemCount) from (select category, [Item Purchased],
count(*) as ItemCount from CustomerPurchaseData group by category, [Item Purchased]) as Subquery
where Subquery.category = CustomerPurchaseData.Category);

-- Calculate the average review rating for items in each category, sorted in descending order of average review rating?
select category, avg([Review Rating]) as "Average Review Rating" from CustomerPurchaseData group by category
order by "Average Review Rating" desc;

-- Calculate the distribution of preferred payment methods for each gender, showing the percentage of customers using each payment method?
select gender, [Preferred Payment Method], count(*) as "Customer Count",
round(count(*) * 100.0 / sum(count(*)) over(partition by gender), 2) as "Payment Method Percentage"
from CustomerPurchaseData group by gender, [Preferred Payment Method];

-- Identify the most common color for each category of items?
with RankedColors as (select category, color, row_number() over (partition by category order by count(*) desc) as "Color Rank"
from CustomerPurchaseData group by category, color)
select category, color from RankedColors where "Color Rank" = 1;